### ISSUE TITLE
Perbedaan antara var, let, dan const 

### ISSUE THREAD

**Issue by Daezyyy** [Daezyyy/javascripttttt#12]
Isu: Kadang-kadang sulit dipahami perbedaan antara ketiga cara untuk mendeklarasikan variabel ini, terutama dalam hal hoisting dan ruang lingkup (scope).

**Comment by DillonAdriyan** [comment]
berikut adalah contoh perbedaan antara penggunaan `var`, `let`, dan `const` dalam JavaScript:

### Penggunaan `var`:
```javascript
function exampleVar() {
    if (true) {
        var varVariable = "Variabel dengan var";
    }
    console.log(varVariable); // variabel var bisa diakses di luar blok if
}

exampleVar(); // Output: Variabel dengan var
console.log(varVariable); // Output: ReferenceError: varVariable is not defined
```

### Penggunaan `let`:
```javascript
function exampleLet() {
    if (true) {
        let letVariable = "Variabel dengan let";
    }
    console.log(letVariable); // variabel let tidak bisa diakses di luar blok if
}

exampleLet(); // Output: ReferenceError: letVariable is not defined
```

### Penggunaan `const`:
```javascript
function exampleConst() {
    const pi = 3.14;
    pi = 3; // Error: Assignment to constant variable
    console.log(pi);
}

exampleConst(); // Output: TypeError: Assignment to constant variable
```

Penjelasan singkat:
- `var` memiliki hoisting (angkat) dan scope fungsi, artinya variabel dapat diakses di luar blok tempat ia dideklarasikan. Ini dapat menyebabkan kebingungan dan masalah dalam pengelolaan variabel.
- `let` diperkenalkan di ES6 dan memiliki scope blok, yang berarti variabel hanya bisa diakses di dalam blok tempat ia dideklarasikan.
- `const` mirip dengan `let` dalam hal scope blok, tetapi variabel yang dideklarasikan dengan `const` harus diinisialisasi dengan nilai dan nilainya tidak dapat diubah setelahnya.

Pemahaman yang jelas tentang perbedaan ini akan membantu dalam memilih jenis deklarasi variabel yang tepat sesuai dengan kebutuhan dan meminimalkan potensi kesalahan dalam pengelolaan variabel.
